on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: docker/login-action@v2
        with:
          registry: 964246069091.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./bridge
          tags: |
            964246069091.dkr.ecr.us-east-1.amazonaws.com/bridge:${{ github.sha }}
            964246069091.dkr.ecr.us-east-1.amazonaws.com/bridge:latest

      - name: Download simulator binary
        run: |
          mkdir -p simulator/bin
          FILE_ID=1byZo6e2xhInRC_FknhRtpQIYriqKfy_L
          FILE_NAME=simulator/bin/TelloLineTraceAirSim.linux.bin.zip
          curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${FILE_ID}" > /dev/null
          CODE="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"
          curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&id=${FILE_ID}&confirm=t" -o ${FILE_NAME}
          unzip -o $FILE_NAME -d simulator/bin
          rm $FILE_NAME

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./simulator
          tags: |
            964246069091.dkr.ecr.us-east-1.amazonaws.com/simulator:${{ github.sha }}
            964246069091.dkr.ecr.us-east-1.amazonaws.com/simulator:latest
