name: Build bridge

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bridge/**'
    types:
      - opened
      - reopend
      - synchronize
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        if: github.event.pull_request.merged == false
        uses: docker/build-push-action@v6
        with:
          push: false
          context: ./bridge

      - name: Build, tag, and push image to Amazon ECR
        id: push_docker_image
        if: github.event.pull_request.merged == true
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./bridge
          tags: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ap-northeast-1.amazonaws.com/bridge:${{ github.sha }}

      - name: Dispatch integration repository workflow
        if: ${{ steps.push_docker_image.outcome == 'success' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository_owner }}/tello_linetrace_integration
          event-type: update_bridge_image
          client-payload: '{ "tag": "${{ github.sha }}" }'
