name: Build simulator

on:
  pull_request:
    branches:
      - main
    paths:
      - 'simulator/**'
    types:
      - opened
      - reopend
      - synchronize
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Unzip simulator binary
        run: |
          unzip -o simulator/LinetraceWorld.zip -d simulator/bin

      - name: Build image
        if: github.event.pull_request.merged == false
        uses: docker/build-push-action@v3
        with:
          push: false
          context: ./simulator

      - name: Build, tag, and push image to Amazon ECR
        id: push_docker_image
        if: github.event.pull_request.merged == true
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./simulator
          tags: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ap-northeast-1.amazonaws.com/simulator:${{ github.sha }}

      - name: Dispatch integration repository workflow
        if: ${{ steps.push_docker_image.outcome == 'success' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
          repository: exmotion-rd/tello_linetrace_integration
          event-type: update_simulator_image
          client-payload: '{ "tag": "${{ github.sha }}" }'
